In [0]:
##Importing Libraries

import pandas as pd
import numpy as np
import nltk
#nltk.download()

In [3]:
##Uploading Dataset in Google Collab

from google.colab import files
upload = files.upload()

Saving train.csv to train.csv


In [0]:
##Reading Dataset
import io
df = pd.read_csv(io.BytesIO(upload['train.csv']))

In [5]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [6]:
df.shape

(20800, 5)

In [7]:

df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [0]:
df = df.dropna()

In [9]:
df.shape

(18285, 5)

In [10]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [0]:
messages = df.copy()

In [0]:
messages.reset_index(inplace=True)

In [0]:
messages.head()

index  id  ...                                               text label
0      0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...     1
1      1   1  ...  Ever get the feeling your life circles the rou...     0
2      2   2  ...  Why the Truth Might Get You Fired October 29, ...     1
3      3   3  ...  Videos 15 Civilians Killed In Single US Airstr...     1
4      4   4  ...  Print \nAn Iranian woman has been sentenced to...     1

[5 rows x 6 columns]

In [0]:
#messages.title[6]
messages['title'][6]

'Benoît Hamon Wins French Socialist Party’s Presidential Nomination - The New York Times'

In [0]:
len(messages)

18285

In [0]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

nltk.download('stopwords')
import re

corpus = []
for i in range(0, len(messages)):
    review = (re.sub('[^a-zA-Z]', ' ', messages['title'][i])).lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [0]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [0]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

## Applying CountVectorizer
## Creating the Bag of Words model

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000, ngram_range=(1,3))

In [0]:
X= cv.fit_transform(corpus).toarray()

In [0]:
#X= X.toarray()

In [0]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [0]:
X.shape

(18285, 5000)

In [0]:
y= messages['label']

In [0]:
#Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [0]:
cv.get_feature_names()[:20]

['abandon',
 'abc',
 'abc news',
 'abduct',
 'abe',
 'abedin',
 'abl',
 'abort',
 'abroad',
 'absolut',
 'abstain',
 'absurd',
 'abus',
 'abus new',
 'abus new york',
 'academi',
 'accept',
 'access',
 'access pipelin',
 'access pipelin protest']

In [0]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [0]:
count_df = pd.DataFrame(X_train, columns=cv.get_feature_names())

In [0]:
count_df

abandon  abc  abc news  abduct  ...  zone new york  zoo  zu  zuckerberg
0            0    0         0       0  ...              0    0   0           0
1            0    0         0       0  ...              0    0   0           0
2            0    0         0       0  ...              0    0   0           0
3            0    0         0       0  ...              0    0   0           0
4            0    0         0       0  ...              0    0   0           0
...        ...  ...       ...     ...  ...            ...  ...  ..         ...
12794        0    0         0       0  ...              0    0   0           0
12795        0    0         0       0  ...              0    0   0           0
12796        0    0         0       0  ...              0    0   0           0
12797        0    0         0       0  ...              0    0   0           0
12798        0    0         0       0  ...              0    0   0           0

[12799 rows x 5000 columns]

## Multinomial NaiveBayes

In [0]:
from sklearn.naive_bayes import  MultinomialNB
classifier = MultinomialNB()

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [0]:
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [0]:
score = accuracy_score(y_test, y_pred)
print('Accuracy: ', np.round(score *100, 2), ' %')

Accuracy:  89.74  %


In [0]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[2780,  321],
       [ 242, 2143]])

## Passive Aggressive Classifier Algorithm

In [0]:
from sklearn.linear_model import  PassiveAggressiveClassifier
passive_clf = PassiveAggressiveClassifier()

In [0]:
passive_clf.fit(X_train, y_train)
y_pred = passive_clf.predict(X_test)

In [0]:
score = accuracy_score(y_test, y_pred)
print('Accuracy: ', np.round(score *100, 2), ' %')

cm = confusion_matrix(y_test, y_pred)
print('\n\n',cm)

Accuracy:  91.09  %


 [[2852  249]
 [ 240 2145]]


In [0]:
##Multinomial Classifier with Hyperparameter

classifier = MultinomialNB(alpha= 0.1)

In [0]:
previous_score= 0

for alpha in np.arange(0, 1, 0.1):
  sub_classifier = MultinomialNB(alpha= alpha)
  sub_classifier.fit(X_train, y_train)
  y_pred = sub_classifier.predict(X_test)
  score = accuracy_score(y_test, y_pred)
  if score > previous_score:
    classifier = sub_classifier

  print(f'Alpha: {alpha}, Score: {score}')


/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:507: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


Alpha: 0.0, Score: 0.8853445133065986
Alpha: 0.1, Score: 0.8982865475756471
Alpha: 0.2, Score: 0.8997448049580751
Alpha: 0.30000000000000004, Score: 0.9001093693036821
Alpha: 0.4, Score: 0.8982865475756471
Alpha: 0.5, Score: 0.8979219832300401
Alpha: 0.6000000000000001, Score: 0.8973751367116296
Alpha: 0.7000000000000001, Score: 0.8970105723660226
Alpha: 0.8, Score: 0.8975574188844331
Alpha: 0.9, Score: 0.8977397010572365


In [0]:
feature_names = cv.get_feature_names()

In [0]:
classifier.coef_[0]

array([ -8.95634439,  -8.95634439,  -9.666586  , ..., -10.83665725,
        -8.66443398,  -9.37032018])

In [0]:
#Most Fake words
sorted(zip(classifier.coef_[0], feature_names))[:20]

[(-10.836657251997297, 'abe'),
 (-10.836657251997297, 'abroad'),
 (-10.836657251997297, 'abus new'),
 (-10.836657251997297, 'abus new york'),
 (-10.836657251997297, 'act new'),
 (-10.836657251997297, 'act new york'),
 (-10.836657251997297, 'advic'),
 (-10.836657251997297, 'advis new'),
 (-10.836657251997297, 'advis new york'),
 (-10.836657251997297, 'affirm'),
 (-10.836657251997297, 'age new'),
 (-10.836657251997297, 'age new york'),
 (-10.836657251997297, 'agenda breitbart'),
 (-10.836657251997297, 'aleppo new'),
 (-10.836657251997297, 'aleppo new york'),
 (-10.836657251997297, 'ali'),
 (-10.836657251997297, 'america breitbart'),
 (-10.836657251997297, 'america great'),
 (-10.836657251997297, 'america new york'),
 (-10.836657251997297, 'american breitbart')]

In [82]:
#Real words
sorted(zip(classifier.coef_[0], feature_names), reverse= True)[:20]

[(-3.9435644999570627, 'trump'),
 (-4.279405523049349, 'hillari'),
 (-4.382332585418199, 'clinton'),
 (-4.893857876870595, 'elect'),
 (-5.19830258266355, 'new'),
 (-5.226371787117323, 'video'),
 (-5.276403062749337, 'us'),
 (-5.293652304570334, 'comment'),
 (-5.370474164440036, 'hillari clinton'),
 (-5.379912648854741, 'war'),
 (-5.443534883730949, 'fbi'),
 (-5.490078961832006, 'email'),
 (-5.500723021877953, 'vote'),
 (-5.52235718094265, 'world'),
 (-5.601989912525715, 'obama'),
 (-5.688516988916647, 'donald'),
 (-5.7080743267377425, 'russia'),
 (-5.721328331230918, 'donald trump'),
 (-5.797542486579172, 'say'),
 (-5.82676297312576, 'america')]

## TFIDF

In [34]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
ps = PorterStemmer()
lemma = WordNetLemmatizer()

nltk.download('wordnet')
nltk.download('stopwords')
import re

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [0]:
corpus = []
for i in range(0, len(messages)):
    review = (re.sub('[^a-zA-Z]', ' ', messages['title'][i])).lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [0]:
corpus = []
for i in range(0, len(messages)):
    review = (re.sub('[^a-zA-Z]', ' ', messages['title'][i])).lower()
    review = review.split()
    
    review = [lemma.lemmatize(word, pos='n') for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [0]:
tfidf_vec = TfidfVectorizer(max_features=5000, ngram_range=(1,3))

In [0]:
X= tfidf_vec.fit_transform(corpus).toarray()

In [0]:
y= message1['label']

In [56]:
X.shape

(18285, 5000)

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [0]:
tfidf_df= pd.DataFrame(X_train, columns=tfidf_vec.get_feature_names())

In [59]:
tfidf_df.head(10)

abandon  abandoned  abc  abc news  ...  zone new  zone new york   zu  zuckerberg
0      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0
1      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0
2      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0
3      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0
4      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0
5      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0
6      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0
7      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0
8      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0
9      0.0        0.0  0.0       0.0  ...       0.0            0.0  0.0         0.0

[10 rows x 5000 columns]

## Multinomial NaiveBayes

In [0]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [0]:
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [64]:
confusion_matrix(y_test, y_pred)

array([[2924,  160],
       [ 533, 1869]])

In [65]:
accuracy_score(y_test, y_pred)

0.8736784542471746